server:
  port: ${PORT:8020}
spring:
  application:
    name: customer-service
  resources:
    static-locations: classpath:static
  mvc:
    view:
      prefix: /
      suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka,http://127.0.0.1:9002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true