server:
  port: ${PORT:10001}
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka,http://127.0.0.1:9002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
zuul:
  routes:
    teacher-service:
      path: /demoteacher/**
      serviceId: teacher-service
  strip-prefix: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 2000