server:
  port: ${PORT:8010}
spring:
  application:
    name: teacher-service
  resources:
    static-locations: static
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka,http://127.0.0.1:9002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true